var CanvasKitInit = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var E=moduleArg,ba,ca,ha=new Promise((a,d)=>{ba=a;ca=d}),ja="object"==typeof window,ka="undefined"!=typeof WorkerGlobalScope,la="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;if(la){const {createRequire:a}=await import("module");var require=a(import.meta.url)}
(function(a){a.Ka=a.Ka||[];a.Ka.push(function(){a.MakeSWCanvasSurface=function(d){var g=d,h="undefined"!==typeof OffscreenCanvas&&g instanceof OffscreenCanvas;if(!("undefined"!==typeof HTMLCanvasElement&&g instanceof HTMLCanvasElement||h||(g=document.getElementById(d),g)))throw"Canvas with id "+d+" was not found";if(d=a.MakeSurface(g.width,g.height))d.cb=g;return d};a.MakeCanvasSurface||(a.MakeCanvasSurface=a.MakeSWCanvasSurface);a.MakeSurface=function(d,g){var h={width:d,height:g,colorType:a.ColorType.RGBA_8888,
alphaType:a.AlphaType.Unpremul,colorSpace:a.ColorSpace.SRGB},m=d*g*4,r=a._malloc(m);if(h=a.Surface._makeRasterDirect(h,r,4*d))h.cb=null,h.rb=d,h.ob=g,h.pb=m,h.gb=r,h.getCanvas().clear(a.TRANSPARENT);return h};a.MakeRasterDirectSurface=function(d,g,h){return a.Surface._makeRasterDirect(d,g.byteOffset,h)};a.Surface.prototype.flush=function(d){this._flush();if(this.cb){var g=new Uint8ClampedArray(a.HEAPU8.buffer,this.gb,this.pb);g=new ImageData(g,this.rb,this.ob);d?this.cb.getContext("2d").putImageData(g,
0,0,d[0],d[1],d[2]-d[0],d[3]-d[1]):this.cb.getContext("2d").putImageData(g,0,0)}};a.Surface.prototype.dispose=function(){this.gb&&a._free(this.gb);this.delete()};a.Eb=a.Eb||function(){};a.hb=a.hb||function(){return null}})})(E);
(function(a){function d(c,b,e,f,k){for(var n=0;n<c.length;n++)b[n*e+(n*k+f+e)%e]=c[n];return b}function g(c){for(var b=c*c,e=Array(b);b--;)e[b]=0===b%(c+1)?1:0;return e}function h(c){return(t(255*c[3])<<24|t(255*c[0])<<16|t(255*c[1])<<8|t(255*c[2])<<0)>>>0}function m(c){if(c&&c._ck)return c;if(c instanceof Float32Array){for(var b=Math.floor(c.length/4),e=new Uint32Array(b),f=0;f<b;f++)e[f]=h(c.slice(4*f,4*(f+1)));return e}if(c instanceof Uint32Array)return c;if(c instanceof Array&&c[0]instanceof Float32Array)return c.map(h)}
function r(c){if(void 0===c)return 1;var b=parseFloat(c);return c&&-1!==c.indexOf("%")?b/100:b}function t(c){return Math.round(Math.max(0,Math.min(c||0,255)))}function p(c,b){b&&b._ck||a._free(c)}function q(c,b,e){if(!c||!c.length)return G;if(c&&c._ck)return c.byteOffset;var f=a[b].BYTES_PER_ELEMENT;e||=a._malloc(c.length*f);a[b].set(c,e/f);return e}function y(c){var b={Pa:G,count:c.length,colorType:a.ColorType.RGBA_F32};if(c instanceof Float32Array)b.Pa=q(c,"HEAPF32"),b.count=c.length/4;else if(c instanceof
Uint32Array)b.Pa=q(c,"HEAPU32"),b.colorType=a.ColorType.RGBA_8888;else if(c instanceof Array){if(c&&c.length){for(var e=a._malloc(16*c.length),f=0,k=e/4,n=0;n<c.length;n++)for(var u=0;4>u;u++)a.HEAPF32[k+f]=c[n][u],f++;c=e}else c=G;b.Pa=c}else throw"Invalid argument to copyFlexibleColorArray, Not a color array "+typeof c;return b}function w(c){if(!c)return G;var b=ya.toTypedArray();if(c.length){if(6===c.length||9===c.length)return q(c,"HEAPF32",da),6===c.length&&a.HEAPF32.set(oc,6+da/4),da;if(16===
c.length)return b[0]=c[0],b[1]=c[1],b[2]=c[3],b[3]=c[4],b[4]=c[5],b[5]=c[7],b[6]=c[12],b[7]=c[13],b[8]=c[15],da;throw"invalid matrix size";}if(void 0===c.m11)throw"invalid matrix argument";b[0]=c.m11;b[1]=c.m21;b[2]=c.m41;b[3]=c.m12;b[4]=c.m22;b[5]=c.m42;b[6]=c.m14;b[7]=c.m24;b[8]=c.m44;return da}function z(c){if(!c)return G;var b=nb.toTypedArray();if(c.length){if(16!==c.length&&6!==c.length&&9!==c.length)throw"invalid matrix size";if(16===c.length)return q(c,"HEAPF32",za);b.fill(0);b[0]=c[0];b[1]=
c[1];b[3]=c[2];b[4]=c[3];b[5]=c[4];b[7]=c[5];b[10]=1;b[12]=c[6];b[13]=c[7];b[15]=c[8];6===c.length&&(b[12]=0,b[13]=0,b[15]=1);return za}if(void 0===c.m11)throw"invalid matrix argument";b[0]=c.m11;b[1]=c.m21;b[2]=c.m31;b[3]=c.m41;b[4]=c.m12;b[5]=c.m22;b[6]=c.m32;b[7]=c.m42;b[8]=c.m13;b[9]=c.m23;b[10]=c.m33;b[11]=c.m43;b[12]=c.m14;b[13]=c.m24;b[14]=c.m34;b[15]=c.m44;return za}function A(c,b){return q(c,"HEAPF32",b||ua)}function M(c,b,e,f){var k=ob.toTypedArray();k[0]=c;k[1]=b;k[2]=e;k[3]=f;return ua}
function K(c){for(var b=new Float32Array(4),e=0;4>e;e++)b[e]=a.HEAPF32[c/4+e];return b}function D(c,b){return q(c,"HEAPF32",b||P)}function Q(c,b){return q(c,"HEAPF32",b||pb)}function ea(){for(var c=0,b=0;b<arguments.length-1;b+=2)c+=arguments[b]*arguments[b+1];return c}function R(c,b,e){for(var f=Array(c.length),k=0;k<e;k++)for(var n=0;n<e;n++){for(var u=0,x=0;x<e;x++)u+=c[e*k+x]*b[e*x+n];f[k*e+n]=u}return f}function ia(c,b){for(var e=R(b[0],b[1],c),f=2;f<b.length;)e=R(e,b[f],c),f++;return e}a.Color=
function(c,b,e,f){void 0===f&&(f=1);return a.Color4f(t(c)/255,t(b)/255,t(e)/255,f)};a.ColorAsInt=function(c,b,e,f){void 0===f&&(f=255);return(t(f)<<24|t(c)<<16|t(b)<<8|t(e)<<0&268435455)>>>0};a.Color4f=function(c,b,e,f){void 0===f&&(f=1);return Float32Array.of(c,b,e,f)};Object.defineProperty(a,"TRANSPARENT",{get:function(){return a.Color4f(0,0,0,0)}});Object.defineProperty(a,"BLACK",{get:function(){return a.Color4f(0,0,0,1)}});Object.defineProperty(a,"WHITE",{get:function(){return a.Color4f(1,1,1,
1)}});Object.defineProperty(a,"RED",{get:function(){return a.Color4f(1,0,0,1)}});Object.defineProperty(a,"GREEN",{get:function(){return a.Color4f(0,1,0,1)}});Object.defineProperty(a,"BLUE",{get:function(){return a.Color4f(0,0,1,1)}});Object.defineProperty(a,"YELLOW",{get:function(){return a.Color4f(1,1,0,1)}});Object.defineProperty(a,"CYAN",{get:function(){return a.Color4f(0,1,1,1)}});Object.defineProperty(a,"MAGENTA",{get:function(){return a.Color4f(1,0,1,1)}});a.getColorComponents=function(c){return[Math.floor(255*
c[0]),Math.floor(255*c[1]),Math.floor(255*c[2]),c[3]]};a.parseColorString=function(c,b){c=c.toLowerCase();if(c.startsWith("#")){b=255;switch(c.length){case 9:b=parseInt(c.slice(7,9),16);case 7:var e=parseInt(c.slice(1,3),16);var f=parseInt(c.slice(3,5),16);var k=parseInt(c.slice(5,7),16);break;case 5:b=17*parseInt(c.slice(4,5),16);case 4:e=17*parseInt(c.slice(1,2),16),f=17*parseInt(c.slice(2,3),16),k=17*parseInt(c.slice(3,4),16)}return a.Color(e,f,k,b/255)}return c.startsWith("rgba")?(c=c.slice(5,
-1),c=c.split(","),a.Color(+c[0],+c[1],+c[2],r(c[3]))):c.startsWith("rgb")?(c=c.slice(4,-1),c=c.split(","),a.Color(+c[0],+c[1],+c[2],r(c[3]))):c.startsWith("gray(")||c.startsWith("hsl")||!b||(c=b[c],void 0===c)?a.BLACK:c};a.multiplyByAlpha=function(c,b){c=c.slice();c[3]=Math.max(0,Math.min(c[3]*b,1));return c};a.Malloc=function(c,b){var e=a._malloc(b*c.BYTES_PER_ELEMENT);return{_ck:!0,length:b,byteOffset:e,Wa:null,subarray:function(f,k){f=this.toTypedArray().subarray(f,k);f._ck=!0;return f},toTypedArray:function(){if(this.Wa&&
this.Wa.length)return this.Wa;this.Wa=new c(a.HEAPU8.buffer,e,b);this.Wa._ck=!0;return this.Wa}}};a.Free=function(c){a._free(c.byteOffset);c.byteOffset=G;c.toTypedArray=null;c.Wa=null};var da=G,ya,za=G,nb,ua=G,ob,fa,P=G,Hb,ta=G,Ib,qb=G,Jb,rb=G,Ra,Ja=G,Kb,pb=G,Lb,Mb=G,oc=Float32Array.of(0,0,1),G=0;a.onRuntimeInitialized=function(){function c(b,e,f,k,n,u,x){u||(u=4*k.width,k.colorType===a.ColorType.RGBA_F16?u*=2:k.colorType===a.ColorType.RGBA_F32&&(u*=4));var C=u*k.height;var B=n?n.byteOffset:a._malloc(C);
if(x?!b._readPixels(k,B,u,e,f,x):!b._readPixels(k,B,u,e,f))return n||a._free(B),null;if(n)return n.toTypedArray();switch(k.colorType){case a.ColorType.RGBA_8888:case a.ColorType.RGBA_F16:b=(new Uint8Array(a.HEAPU8.buffer,B,C)).slice();break;case a.ColorType.RGBA_F32:b=(new Float32Array(a.HEAPU8.buffer,B,C)).slice();break;default:return null}a._free(B);return b}ob=a.Malloc(Float32Array,4);ua=ob.byteOffset;nb=a.Malloc(Float32Array,16);za=nb.byteOffset;ya=a.Malloc(Float32Array,9);da=ya.byteOffset;Kb=
a.Malloc(Float32Array,12);pb=Kb.byteOffset;Lb=a.Malloc(Float32Array,12);Mb=Lb.byteOffset;fa=a.Malloc(Float32Array,4);P=fa.byteOffset;Hb=a.Malloc(Float32Array,4);ta=Hb.byteOffset;Ib=a.Malloc(Float32Array,3);qb=Ib.byteOffset;Jb=a.Malloc(Float32Array,3);rb=Jb.byteOffset;Ra=a.Malloc(Int32Array,4);Ja=Ra.byteOffset;a.ColorSpace.SRGB=a.ColorSpace._MakeSRGB();a.ColorSpace.DISPLAY_P3=a.ColorSpace._MakeDisplayP3();a.ColorSpace.ADOBE_RGB=a.ColorSpace._MakeAdobeRGB();a.GlyphRunFlags={IsWhiteSpace:a._GlyphRunFlags_isWhiteSpace};
a.Path.MakeFromCmds=function(b){var e=q(b,"HEAPF32"),f=a.Path._MakeFromCmds(e,b.length);p(e,b);return f};a.Path.MakeFromVerbsPointsWeights=function(b,e,f){var k=q(b,"HEAPU8"),n=q(e,"HEAPF32"),u=q(f,"HEAPF32"),x=a.Path._MakeFromVerbsPointsWeights(k,b.length,n,e.length/2,u,f&&f.length||0);p(k,b);p(n,e);p(u,f);return x};a.PathBuilder.prototype.addArc=function(b,e,f){b=D(b);this._addArc(b,e,f);return this};a.PathBuilder.prototype.addCircle=function(b,e,f,k){this._addCircle(b,e,f,!!k);return this};a.PathBuilder.prototype.addOval=
function(b,e,f){void 0===f&&(f=1);b=D(b);this._addOval(b,!!e,f);return this};a.PathBuilder.prototype.addPath=function(){var b=Array.prototype.slice.call(arguments),e=b[0],f=!1;"boolean"===typeof b[b.length-1]&&(f=b.pop());if(1===b.length)this._addPath(e,1,0,0,0,1,0,0,0,1,f);else if(2===b.length)b=b[1],this._addPath(e,b[0],b[1],b[2],b[3],b[4],b[5],b[6]||0,b[7]||0,b[8]||1,f);else if(7===b.length||10===b.length)this._addPath(e,b[1],b[2],b[3],b[4],b[5],b[6],b[7]||0,b[8]||0,b[9]||1,f);else return null;
return this};a.PathBuilder.prototype.addPolygon=function(b,e){var f=q(b,"HEAPF32");this._addPolygon(f,b.length/2,e);p(f,b);return this};a.PathBuilder.prototype.addRect=function(b,e){b=D(b);this._addRect(b,!!e);return this};a.PathBuilder.prototype.addRRect=function(b,e){b=Q(b);this._addRRect(b,!!e);return this};a.PathBuilder.prototype.addVerbsPointsWeights=function(b,e,f){var k=q(b,"HEAPU8"),n=q(e,"HEAPF32"),u=q(f,"HEAPF32");this._addVerbsPointsWeights(k,b.length,n,e.length/2,u,f&&f.length||0);p(k,
b);p(n,e);p(u,f);return this};a.PathBuilder.prototype.arc=function(b,e,f,k,n,u){b=a.LTRBRect(b-f,e-f,b+f,e+f);n=(n-k)/Math.PI*180-360*!!u;k=(new a.PathBuilder).addArc(b,k/Math.PI*180,n).detachAndDelete();this.addPath(k,!0);k.delete();return this};a.PathBuilder.prototype.arcToOval=function(b,e,f,k){b=D(b);this._arcToOval(b,e,f,k);return this};a.PathBuilder.prototype.arcToRotated=function(b,e,f,k,n,u,x){this._arcToRotated(b,e,f,!!k,!!n,u,x);return this};a.PathBuilder.prototype.arcToTangent=function(b,
e,f,k,n){this._arcToTangent(b,e,f,k,n);return this};a.PathBuilder.prototype.close=function(){this._close();return this};a.PathBuilder.prototype.conicTo=function(b,e,f,k,n){this._conicTo(b,e,f,k,n);return this};a.Path.prototype.computeTightBounds=function(b){this._computeTightBounds(P);var e=fa.toTypedArray();return b?(b.set(e),b):e.slice()};a.PathBuilder.prototype.cubicTo=function(b,e,f,k,n,u){this._cubicTo(b,e,f,k,n,u);return this};a.PathBuilder.prototype.detachAndDelete=function(){var b=this.detach();
this.delete();return b};a.Path.prototype.getBounds=function(b){this._getBounds(P);var e=fa.toTypedArray();return b?(b.set(e),b):e.slice()};a.PathBuilder.prototype.getBounds=function(b){this._getBounds(P);var e=fa.toTypedArray();return b?(b.set(e),b):e.slice()};a.PathBuilder.prototype.lineTo=function(b,e){this._lineTo(b,e);return this};a.PathBuilder.prototype.moveTo=function(b,e){this._moveTo(b,e);return this};a.PathBuilder.prototype.offset=function(b,e){this._transform(1,0,b,0,1,e,0,0,1);return this};
a.PathBuilder.prototype.quadTo=function(b,e,f,k){this._quadTo(b,e,f,k);return this};a.PathBuilder.prototype.rArcTo=function(b,e,f,k,n,u,x){this._rArcTo(b,e,f,k,n,u,x);return this};a.PathBuilder.prototype.rConicTo=function(b,e,f,k,n){this._rConicTo(b,e,f,k,n);return this};a.PathBuilder.prototype.rCubicTo=function(b,e,f,k,n,u){this._rCubicTo(b,e,f,k,n,u);return this};a.PathBuilder.prototype.rLineTo=function(b,e){this._rLineTo(b,e);return this};a.PathBuilder.prototype.rMoveTo=function(b,e){this._rMoveTo(b,
e);return this};a.PathBuilder.prototype.rQuadTo=function(b,e,f,k){this._rQuadTo(b,e,f,k);return this};a.Path.prototype.makeStroked=function(b){b=b||{};b.width=b.width||1;b.miter_limit=b.miter_limit||4;b.cap=b.cap||a.StrokeCap.Butt;b.join=b.join||a.StrokeJoin.Miter;b.precision=b.precision||1;return this._makeStroked(b)};a.PathBuilder.prototype.transform=function(){if(1===arguments.length){var b=arguments[0];this._transform(b[0],b[1],b[2],b[3],b[4],b[5],b[6]||0,b[7]||0,b[8]||1)}else if(6===arguments.length||
9===arguments.length)b=arguments,this._transform(b[0],b[1],b[2],b[3],b[4],b[5],b[6]||0,b[7]||0,b[8]||1);else throw"transform expected to take 1 or 9 arguments. Got "+arguments.length;return this};a.Path.prototype.makeTrimmed=function(b,e,f){return this._makeTrimmed(b,e,!!f)};a.Image.prototype.encodeToBytes=function(b,e){var f=a.hb();b=b||a.ImageFormat.PNG;e=e||100;return f?this._encodeToBytes(b,e,f):this._encodeToBytes(b,e)};a.Image.prototype.makeShaderCubic=function(b,e,f,k,n){n=w(n);return this._makeShaderCubic(b,
e,f,k,n)};a.Image.prototype.makeShaderOptions=function(b,e,f,k,n){n=w(n);return this._makeShaderOptions(b,e,f,k,n)};a.Image.prototype.readPixels=function(b,e,f,k,n){return c(this,b,e,f,k,n,a.hb())};a.Canvas.prototype.clear=function(b){b=A(b);this._clear(b)};a.Canvas.prototype.clipRRect=function(b,e,f){b=Q(b);this._clipRRect(b,e,f)};a.Canvas.prototype.clipRect=function(b,e,f){b=D(b);this._clipRect(b,e,f)};a.Canvas.prototype.concat=function(b){b=z(b);this._concat(b)};a.Canvas.prototype.drawArc=function(b,
e,f,k,n){b=D(b);this._drawArc(b,e,f,k,n)};a.Canvas.prototype.drawAtlas=function(b,e,f,k,n,u,x){if(b&&k&&e&&f&&e.length===f.length){n||(n=a.BlendMode.SrcOver);var C=q(e,"HEAPF32"),B=q(f,"HEAPF32"),I=f.length/4,J=q(m(u),"HEAPU32");if(x&&"B"in x&&"C"in x)this._drawAtlasCubic(b,B,C,J,I,n,x.B,x.C,k);else{let l=a.FilterMode.Linear,v=a.MipmapMode.None;x&&(l=x.filter,"mipmap"in x&&(v=x.mipmap));this._drawAtlasOptions(b,B,C,J,I,n,l,v,k)}p(C,e);p(B,f);p(J,u)}};a.Canvas.prototype.drawCircle=function(b,e,f,k){this._drawCircle(b,
e,f,k)};a.Canvas.prototype.drawColor=function(b,e){b=A(b);void 0!==e?this._drawColor(b,e):this._drawColor(b)};a.Canvas.prototype.drawColorInt=function(b,e){this._drawColorInt(b,e||a.BlendMode.SrcOver)};a.Canvas.prototype.drawColorComponents=function(b,e,f,k,n){b=M(b,e,f,k);void 0!==n?this._drawColor(b,n):this._drawColor(b)};a.Canvas.prototype.drawDRRect=function(b,e,f){b=Q(b,pb);e=Q(e,Mb);this._drawDRRect(b,e,f)};a.Canvas.prototype.drawImage=function(b,e,f,k){this._drawImage(b,e,f,k||null)};a.Canvas.prototype.drawImageCubic=
function(b,e,f,k,n,u){this._drawImageCubic(b,e,f,k,n,u||null)};a.Canvas.prototype.drawImageOptions=function(b,e,f,k,n,u){this._drawImageOptions(b,e,f,k,n,u||null)};a.Canvas.prototype.drawImageNine=function(b,e,f,k,n){e=q(e,"HEAP32",Ja);f=D(f);this._drawImageNine(b,e,f,k,n||null)};a.Canvas.prototype.drawImageRect=function(b,e,f,k,n){D(e,P);D(f,ta);this._drawImageRect(b,P,ta,k,!!n)};a.Canvas.prototype.drawImageRectCubic=function(b,e,f,k,n,u){D(e,P);D(f,ta);this._drawImageRectCubic(b,P,ta,k,n,u||null)};
a.Canvas.prototype.drawImageRectOptions=function(b,e,f,k,n,u){D(e,P);D(f,ta);this._drawImageRectOptions(b,P,ta,k,n,u||null)};a.Canvas.prototype.drawLine=function(b,e,f,k,n){this._drawLine(b,e,f,k,n)};a.Canvas.prototype.drawOval=function(b,e){b=D(b);this._drawOval(b,e)};a.Canvas.prototype.drawPaint=function(b){this._drawPaint(b)};a.Canvas.prototype.drawParagraph=function(b,e,f){this._drawParagraph(b,e,f)};a.Canvas.prototype.drawPatch=function(b,e,f,k,n){if(24>b.length)throw"Need 12 cubic points";if(e&&
4>e.length)throw"Need 4 colors";if(f&&8>f.length)throw"Need 4 shader coordinates";const u=q(b,"HEAPF32"),x=e?q(m(e),"HEAPU32"):G,C=f?q(f,"HEAPF32"):G;k||(k=a.BlendMode.Modulate);this._drawPatch(u,x,C,k,n);p(C,f);p(x,e);p(u,b)};a.Canvas.prototype.drawPath=function(b,e){this._drawPath(b,e)};a.Canvas.prototype.drawPicture=function(b){this._drawPicture(b)};a.Canvas.prototype.drawPoints=function(b,e,f){var k=q(e,"HEAPF32");this._drawPoints(b,k,e.length/2,f);p(k,e)};a.Canvas.prototype.drawRRect=function(b,
e){b=Q(b);this._drawRRect(b,e)};a.Canvas.prototype.drawRect=function(b,e){b=D(b);this._drawRect(b,e)};a.Canvas.prototype.drawRect4f=function(b,e,f,k,n){this._drawRect4f(b,e,f,k,n)};a.Canvas.prototype.drawShadow=function(b,e,f,k,n,u,x){var C=q(n,"HEAPF32"),B=q(u,"HEAPF32");e=q(e,"HEAPF32",qb);f=q(f,"HEAPF32",rb);this._drawShadow(b,e,f,k,C,B,x);p(C,n);p(B,u)};a.getShadowLocalBounds=function(b,e,f,k,n,u,x){b=w(b);f=q(f,"HEAPF32",qb);k=q(k,"HEAPF32",rb);if(!this._getShadowLocalBounds(b,e,f,k,n,u,P))return null;
e=fa.toTypedArray();return x?(x.set(e),x):e.slice()};a.Canvas.prototype.drawTextBlob=function(b,e,f,k){this._drawTextBlob(b,e,f,k)};a.Canvas.prototype.drawVertices=function(b,e,f){this._drawVertices(b,e,f)};a.Canvas.prototype.getDeviceClipBounds=function(b){this._getDeviceClipBounds(Ja);var e=Ra.toTypedArray();b?b.set(e):b=e.slice();return b};a.Canvas.prototype.quickReject=function(b){b=D(b);return this._quickReject(b)};a.Canvas.prototype.getLocalToDevice=function(){this._getLocalToDevice(za);for(var b=
za,e=Array(16),f=0;16>f;f++)e[f]=a.HEAPF32[b/4+f];return e};a.Canvas.prototype.getTotalMatrix=function(){this._getTotalMatrix(da);for(var b=Array(9),e=0;9>e;e++)b[e]=a.HEAPF32[da/4+e];return b};a.Canvas.prototype.makeSurface=function(b){b=this._makeSurface(b);b.Ya=this.Ya;return b};a.Canvas.prototype.readPixels=function(b,e,f,k,n){return c(this,b,e,f,k,n)};a.Canvas.prototype.saveLayer=function(b,e,f,k,n){e=D(e);return this._saveLayer(b||null,e,f||null,k||0,n||a.TileMode.Clamp)};a.Canvas.prototype.writePixels=
function(b,e,f,k,n,u,x,C){if(b.byteLength%(e*f))throw"pixels length must be a multiple of the srcWidth * srcHeight";var B=b.byteLength/(e*f);u=u||a.AlphaType.Unpremul;x=x||a.ColorType.RGBA_8888;C=C||a.ColorSpace.SRGB;var I=B*e;B=q(b,"HEAPU8");e=this._writePixels({width:e,height:f,colorType:x,alphaType:u,colorSpace:C},B,I,k,n);p(B,b);return e};a.ColorFilter.MakeBlend=function(b,e,f){b=A(b);f=f||a.ColorSpace.SRGB;return a.ColorFilter._MakeBlend(b,e,f)};a.ColorFilter.MakeMatrix=function(b){if(!b||20!==
b.length)throw"invalid color matrix";var e=q(b,"HEAPF32"),f=a.ColorFilter._makeMatrix(e);p(e,b);return f};a.ContourMeasure.prototype.getPosTan=function(b,e){this._getPosTan(b,P);b=fa.toTypedArray();return e?(e.set(b),e):b.slice()};a.ImageFilter.prototype.getOutputBounds=function(b,e,f){b=D(b,P);e=w(e);this._getOutputBounds(b,e,Ja);e=Ra.toTypedArray();return f?(f.set(e),f):e.slice()};a.ImageFilter.MakeDropShadow=function(b,e,f,k,n,u){n=A(n,ua);return a.ImageFilter._MakeDropShadow(b,e,f,k,n,u)};a.ImageFilter.MakeDropShadowOnly=
function(b,e,f,k,n,u){n=A(n,ua);return a.ImageFilter._MakeDropShadowOnly(b,e,f,k,n,u)};a.ImageFilter.MakeImage=function(b,e,f,k){f=D(f,P);k=D(k,ta);if("B"in e&&"C"in e)return a.ImageFilter._MakeImageCubic(b,e.B,e.C,f,k);const n=e.filter;let u=a.MipmapMode.None;"mipmap"in e&&(u=e.mipmap);return a.ImageFilter._MakeImageOptions(b,n,u,f,k)};a.ImageFilter.MakeMatrixTransform=function(b,e,f){b=w(b);if("B"in e&&"C"in e)return a.ImageFilter._MakeMatrixTransformCubic(b,e.B,e.C,f);const k=e.filter;let n=a.MipmapMode.None;
"mipmap"in e&&(n=e.mipmap);return a.ImageFilter._MakeMatrixTransformOptions(b,k,n,f)};a.Paint.prototype.getColor=function(){this._getColor(ua);return K(ua)};a.Paint.prototype.setColor=function(b,e){e=e||null;b=A(b);this._setColor(b,e)};a.Paint.prototype.setColorComponents=function(b,e,f,k,n){n=n||null;b=M(b,e,f,k);this._setColor(b,n)};a.Path.prototype.getPoint=function(b,e){this._getPoint(b,P);b=fa.toTypedArray();return e?(e[0]=b[0],e[1]=b[1],e):b.slice(0,2)};a.Picture.prototype.makeShader=function(b,
e,f,k,n){k=w(k);n=D(n);return this._makeShader(b,e,f,k,n)};a.Picture.prototype.cullRect=function(b){this._cullRect(P);var e=fa.toTypedArray();return b?(b.set(e),b):e.slice()};a.PictureRecorder.prototype.beginRecording=function(b,e){b=D(b);return this._beginRecording(b,!!e)};a.Surface.prototype.getCanvas=function(){var b=this._getCanvas();b.Ya=this.Ya;return b};a.Surface.prototype.makeImageSnapshot=function(b){b=q(b,"HEAP32",Ja);return this._makeImageSnapshot(b)};a.Surface.prototype.makeSurface=function(b){b=
this._makeSurface(b);b.Ya=this.Ya;return b};a.Surface.prototype.qb=function(b,e){this.Xa||(this.Xa=this.getCanvas());return requestAnimationFrame(function(){b(this.Xa);this.flush(e)}.bind(this))};a.Surface.prototype.requestAnimationFrame||(a.Surface.prototype.requestAnimationFrame=a.Surface.prototype.qb);a.Surface.prototype.nb=function(b,e){this.Xa||(this.Xa=this.getCanvas());requestAnimationFrame(function(){b(this.Xa);this.flush(e);this.dispose()}.bind(this))};a.Surface.prototype.drawOnce||(a.Surface.prototype.drawOnce=
a.Surface.prototype.nb);a.PathEffect.MakeDash=function(b,e){e||=0;if(!b.length||1===b.length%2)throw"Intervals array must have even length";var f=q(b,"HEAPF32");e=a.PathEffect._MakeDash(f,b.length,e);p(f,b);return e};a.PathEffect.MakeLine2D=function(b,e){e=w(e);return a.PathEffect._MakeLine2D(b,e)};a.PathEffect.MakePath2D=function(b,e){b=w(b);return a.PathEffect._MakePath2D(b,e)};a.Shader.MakeColor=function(b,e){e=e||null;b=A(b);return a.Shader._MakeColor(b,e)};a.Shader.Blend=a.Shader.MakeBlend;a.Shader.Color=
a.Shader.MakeColor;a.Shader.MakeLinearGradient=function(b,e,f,k,n,u,x,C){C=C||null;var B=y(f),I=q(k,"HEAPF32");x=x||0;u=w(u);var J=fa.toTypedArray();J.set(b);J.set(e,2);b=a.Shader._MakeLinearGradient(P,B.Pa,B.colorType,I,B.count,n,x,u,C);p(B.Pa,f);k&&p(I,k);return b};a.Shader.MakeRadialGradient=function(b,e,f,k,n,u,x,C){C=C||null;var B=y(f),I=q(k,"HEAPF32");x=x||0;u=w(u);b=a.Shader._MakeRadialGradient(b[0],b[1],e,B.Pa,B.colorType,I,B.count,n,x,u,C);p(B.Pa,f);k&&p(I,k);return b};a.Shader.MakeSweepGradient=
function(b,e,f,k,n,u,x,C,B,I){I=I||null;var J=y(f),l=q(k,"HEAPF32");x=x||0;C=C||0;B=B||360;u=w(u);b=a.Shader._MakeSweepGradient(b,e,J.Pa,J.colorType,l,J.count,n,C,B,x,u,I);p(J.Pa,f);k&&p(l,k);return b};a.Shader.MakeTwoPointConicalGradient=function(b,e,f,k,n,u,x,C,B,I){I=I||null;var J=y(n),l=q(u,"HEAPF32");B=B||0;C=w(C);var v=fa.toTypedArray();v.set(b);v.set(f,2);b=a.Shader._MakeTwoPointConicalGradient(P,e,k,J.Pa,J.colorType,l,J.count,x,B,C,I);p(J.Pa,n);u&&p(l,u);return b};a.Vertices.prototype.bounds=
function(b){this._bounds(P);var e=fa.toTypedArray();return b?(b.set(e),b):e.slice()};a.Ka&&a.Ka.forEach(function(b){b()})};a.computeTonalColors=function(c){var b=q(c.ambient,"HEAPF32"),e=q(c.spot,"HEAPF32");this._computeTonalColors(b,e);var f={ambient:K(b),spot:K(e)};p(b,c.ambient);p(e,c.spot);return f};a.LTRBRect=function(c,b,e,f){return Float32Array.of(c,b,e,f)};a.XYWHRect=function(c,b,e,f){return Float32Array.of(c,b,c+e,b+f)};a.LTRBiRect=function(c,b,e,f){return Int32Array.of(c,b,e,f)};a.XYWHiRect=
function(c,b,e,f){return Int32Array.of(c,b,c+e,b+f)};a.RRectXY=function(c,b,e){return Float32Array.of(c[0],c[1],c[2],c[3],b,e,b,e,b,e,b,e)};a.MakeAnimatedImageFromEncoded=function(c){c=new Uint8Array(c);var b=a._malloc(c.byteLength);a.HEAPU8.set(c,b);return(c=a._decodeAnimatedImage(b,c.byteLength))?c:null};a.MakeImageFromEncoded=function(c){c=new Uint8Array(c);var b=a._malloc(c.byteLength);a.HEAPU8.set(c,b);return(c=a._decodeImage(b,c.byteLength))?c:null};var Sa=null;a.MakeImageFromCanvasImageSource=
function(c){var b=c.width,e=c.height;Sa||=document.createElement("canvas");Sa.width=b;Sa.height=e;var f=Sa.getContext("2d",{willReadFrequently:!0});f.drawImage(c,0,0);c=f.getImageData(0,0,b,e);return a.MakeImage({width:b,height:e,alphaType:a.AlphaType.Unpremul,colorType:a.ColorType.RGBA_8888,colorSpace:a.ColorSpace.SRGB},c.data,4*b)};a.MakeImage=function(c,b,e){var f=a._malloc(b.length);a.HEAPU8.set(b,f);return a._MakeImage(c,f,b.length,e)};a.MakeVertices=function(c,b,e,f,k,n){var u=k&&k.length||
0,x=0;e&&e.length&&(x|=1);f&&f.length&&(x|=2);void 0===n||n||(x|=4);c=new a._VerticesBuilder(c,b.length/2,u,x);q(b,"HEAPF32",c.positions());c.texCoords()&&q(e,"HEAPF32",c.texCoords());c.colors()&&q(m(f),"HEAPU32",c.colors());c.indices()&&q(k,"HEAPU16",c.indices());return c.detach()};a.Matrix={};a.Matrix.identity=function(){return g(3)};a.Matrix.invert=function(c){var b=c[0]*c[4]*c[8]+c[1]*c[5]*c[6]+c[2]*c[3]*c[7]-c[2]*c[4]*c[6]-c[1]*c[3]*c[8]-c[0]*c[5]*c[7];return b?[(c[4]*c[8]-c[5]*c[7])/b,(c[2]*
c[7]-c[1]*c[8])/b,(c[1]*c[5]-c[2]*c[4])/b,(c[5]*c[6]-c[3]*c[8])/b,(c[0]*c[8]-c[2]*c[6])/b,(c[2]*c[3]-c[0]*c[5])/b,(c[3]*c[7]-c[4]*c[6])/b,(c[1]*c[6]-c[0]*c[7])/b,(c[0]*c[4]-c[1]*c[3])/b]:null};a.Matrix.mapPoints=function(c,b){for(var e=0;e<b.length;e+=2){var f=b[e],k=b[e+1],n=c[6]*f+c[7]*k+c[8],u=c[3]*f+c[4]*k+c[5];b[e]=(c[0]*f+c[1]*k+c[2])/n;b[e+1]=u/n}return b};a.Matrix.multiply=function(){return ia(3,arguments)};a.Matrix.rotated=function(c,b,e){b=b||0;e=e||0;var f=Math.sin(c);c=Math.cos(c);return[c,
-f,ea(f,e,1-c,b),f,c,ea(-f,b,1-c,e),0,0,1]};a.Matrix.scaled=function(c,b,e,f){e=e||0;f=f||0;var k=d([c,b],g(3),3,0,1);return d([e-c*e,f-b*f],k,3,2,0)};a.Matrix.skewed=function(c,b,e,f){e=e||0;f=f||0;var k=d([c,b],g(3),3,1,-1);return d([-c*e,-b*f],k,3,2,0)};a.Matrix.translated=function(c,b){return d(arguments,g(3),3,2,0)};a.Vector={};a.Vector.dot=function(c,b){return c.map(function(e,f){return e*b[f]}).reduce(function(e,f){return e+f})};a.Vector.lengthSquared=function(c){return a.Vector.dot(c,c)};
a.Vector.length=function(c){return Math.sqrt(a.Vector.lengthSquared(c))};a.Vector.mulScalar=function(c,b){return c.map(function(e){return e*b})};a.Vector.add=function(c,b){return c.map(function(e,f){return e+b[f]})};a.Vector.sub=function(c,b){return c.map(function(e,f){return e-b[f]})};a.Vector.dist=function(c,b){return a.Vector.length(a.Vector.sub(c,b))};a.Vector.normalize=function(c){return a.Vector.mulScalar(c,1/a.Vector.length(c))};a.Vector.cross=function(c,b){return[c[1]*b[2]-c[2]*b[1],c[2]*
b[0]-c[0]*b[2],c[0]*b[1]-c[1]*b[0]]};a.M44={};a.M44.identity=function(){return g(4)};a.M44.translated=function(c){return d(c,g(4),4,3,0)};a.M44.scaled=function(c){return d(c,g(4),4,0,1)};a.M44.rotated=function(c,b){return a.M44.rotatedUnitSinCos(a.Vector.normalize(c),Math.sin(b),Math.cos(b))};a.M44.rotatedUnitSinCos=function(c,b,e){var f=c[0],k=c[1];c=c[2];var n=1-e;return[n*f*f+e,n*f*k-b*c,n*f*c+b*k,0,n*f*k+b*c,n*k*k+e,n*k*c-b*f,0,n*f*c-b*k,n*k*c+b*f,n*c*c+e,0,0,0,0,1]};a.M44.lookat=function(c,b,
e){b=a.Vector.normalize(a.Vector.sub(b,c));e=a.Vector.normalize(e);e=a.Vector.normalize(a.Vector.cross(b,e));var f=a.M44.identity();d(e,f,4,0,0);d(a.Vector.cross(e,b),f,4,1,0);d(a.Vector.mulScalar(b,-1),f,4,2,0);d(c,f,4,3,0);c=a.M44.invert(f);return null===c?a.M44.identity():c};a.M44.perspective=function(c,b,e){var f=1/(b-c);e/=2;e=Math.cos(e)/Math.sin(e);return[e,0,0,0,0,e,0,0,0,0,(b+c)*f,2*b*c*f,0,0,-1,1]};a.M44.rc=function(c,b,e){return c[4*b+e]};a.M44.multiply=function(){return ia(4,arguments)};
a.M44.invert=function(c){var b=c[0],e=c[4],f=c[8],k=c[12],n=c[1],u=c[5],x=c[9],C=c[13],B=c[2],I=c[6],J=c[10],l=c[14],v=c[3],F=c[7],L=c[11];c=c[15];var V=b*u-e*n,na=b*x-f*n,oa=b*C-k*n,sa=e*x-f*u,S=e*C-k*u,Aa=f*C-k*x,Ba=B*F-I*v,Ca=B*L-J*v,Da=B*c-l*v,Ea=I*L-J*F,Fa=I*c-l*F,Ga=J*c-l*L,Nb=V*Ga-na*Fa+oa*Ea+sa*Da-S*Ca+Aa*Ba,aa=1/Nb;if(0===Nb||Infinity===aa)return null;V*=aa;na*=aa;oa*=aa;sa*=aa;S*=aa;Aa*=aa;Ba*=aa;Ca*=aa;Da*=aa;Ea*=aa;Fa*=aa;Ga*=aa;b=[u*Ga-x*Fa+C*Ea,x*Da-n*Ga-C*Ca,n*Fa-u*Da+C*Ba,u*Ca-n*Ea-
x*Ba,f*Fa-e*Ga-k*Ea,b*Ga-f*Da+k*Ca,e*Da-b*Fa-k*Ba,b*Ea-e*Ca+f*Ba,F*Aa-L*S+c*sa,L*oa-v*Aa-c*na,v*S-F*oa+c*V,F*na-v*sa-L*V,J*S-I*Aa-l*sa,B*Aa-J*oa+l*na,I*oa-B*S-l*V,B*sa-I*na+J*V];return b.every(function(sb){return!isNaN(sb)&&Infinity!==sb&&-Infinity!==sb})?b:null};a.M44.transpose=function(c){return[c[0],c[4],c[8],c[12],c[1],c[5],c[9],c[13],c[2],c[6],c[10],c[14],c[3],c[7],c[11],c[15]]};a.M44.mustInvert=function(c){c=a.M44.invert(c);if(null===c)throw"Matrix not invertible";return c};a.M44.setupCamera=
function(c,b,e){var f=a.M44.lookat(e.eye,e.coa,e.up);e=a.M44.perspective(e.near,e.far,e.angle);b=[(c[2]-c[0])/2,(c[3]-c[1])/2,b];c=a.M44.multiply(a.M44.translated([(c[0]+c[2])/2,(c[1]+c[3])/2,0]),a.M44.scaled(b));return a.M44.multiply(c,e,f,a.M44.mustInvert(c))};a.ColorMatrix={};a.ColorMatrix.identity=function(){var c=new Float32Array(20);c[0]=1;c[6]=1;c[12]=1;c[18]=1;return c};a.ColorMatrix.scaled=function(c,b,e,f){var k=new Float32Array(20);k[0]=c;k[6]=b;k[12]=e;k[18]=f;return k};var pc=[[6,7,11,
12],[0,10,2,12],[0,1,5,6]];a.ColorMatrix.rotated=function(c,b,e){var f=a.ColorMatrix.identity();c=pc[c];f[c[0]]=e;f[c[1]]=b;f[c[2]]=-b;f[c[3]]=e;return f};a.ColorMatrix.postTranslate=function(c,b,e,f,k){c[4]+=b;c[9]+=e;c[14]+=f;c[19]+=k;return c};a.ColorMatrix.concat=function(c,b){for(var e=new Float32Array(20),f=0,k=0;20>k;k+=5){for(var n=0;4>n;n++)e[f++]=c[k]*b[n]+c[k+1]*b[n+5]+c[k+2]*b[n+10]+c[k+3]*b[n+15];e[f++]=c[k]*b[4]+c[k+1]*b[9]+c[k+2]*b[14]+c[k+3]*b[19]+c[k+4]}return e};(function(c){c.Ka=
c.Ka||[];c.Ka.push(function(){function b(l){l&&(l.dir=0===l.dir?c.TextDirection.RTL:c.TextDirection.LTR);return l}function e(l){if(!l||!l.length)return[];for(var v=[],F=0;F<l.length;F+=5){var L=c.LTRBRect(l[F],l[F+1],l[F+2],l[F+3]),V=c.TextDirection.LTR;0===l[F+4]&&(V=c.TextDirection.RTL);v.push({rect:L,dir:V})}c._free(l.byteOffset);return v}function f(l){l=l||{};void 0===l.weight&&(l.weight=c.FontWeight.Normal);l.width=l.width||c.FontWidth.Normal;l.slant=l.slant||c.FontSlant.Upright;return l}function k(l){if(!l||
!l.length)return G;for(var v=[],F=0;F<l.length;F++){var L=n(l[F]);v.push(L)}return q(v,"HEAPU32")}function n(l){if(C[l])return C[l];var v=ma(l)+1,F=c._malloc(v);pa(l,F,v);return C[l]=F}function u(l){l._colorPtr=A(l.color);l._foregroundColorPtr=G;l._backgroundColorPtr=G;l._decorationColorPtr=G;l.foregroundColor&&(l._foregroundColorPtr=A(l.foregroundColor,B));l.backgroundColor&&(l._backgroundColorPtr=A(l.backgroundColor,I));l.decorationColor&&(l._decorationColorPtr=A(l.decorationColor,J));Array.isArray(l.fontFamilies)&&
l.fontFamilies.length?(l._fontFamiliesPtr=k(l.fontFamilies),l._fontFamiliesLen=l.fontFamilies.length):(l._fontFamiliesPtr=G,l._fontFamiliesLen=0);if(l.locale){var v=l.locale;l._localePtr=n(v);l._localeLen=ma(v)}else l._localePtr=G,l._localeLen=0;if(Array.isArray(l.shadows)&&l.shadows.length){v=l.shadows;var F=v.map(function(S){return S.color||c.BLACK}),L=v.map(function(S){return S.blurRadius||0});l._shadowLen=v.length;for(var V=c._malloc(8*v.length),na=V/4,oa=0;oa<v.length;oa++){var sa=v[oa].offset||
[0,0];c.HEAPF32[na]=sa[0];c.HEAPF32[na+1]=sa[1];na+=2}l._shadowColorsPtr=y(F).Pa;l._shadowOffsetsPtr=V;l._shadowBlurRadiiPtr=q(L,"HEAPF32")}else l._shadowLen=0,l._shadowColorsPtr=G,l._shadowOffsetsPtr=G,l._shadowBlurRadiiPtr=G;Array.isArray(l.fontFeatures)&&l.fontFeatures.length?(v=l.fontFeatures,F=v.map(function(S){return S.name}),L=v.map(function(S){return S.value}),l._fontFeatureLen=v.length,l._fontFeatureNamesPtr=k(F),l._fontFeatureValuesPtr=q(L,"HEAPU32")):(l._fontFeatureLen=0,l._fontFeatureNamesPtr=
G,l._fontFeatureValuesPtr=G);Array.isArray(l.fontVariations)&&l.fontVariations.length?(v=l.fontVariations,F=v.map(function(S){return S.axis}),L=v.map(function(S){return S.value}),l._fontVariationLen=v.length,l._fontVariationAxesPtr=k(F),l._fontVariationValuesPtr=q(L,"HEAPF32")):(l._fontVariationLen=0,l._fontVariationAxesPtr=G,l._fontVariationValuesPtr=G)}function x(l){c._free(l._fontFamiliesPtr);c._free(l._shadowColorsPtr);c._free(l._shadowOffsetsPtr);c._free(l._shadowBlurRadiiPtr);c._free(l._fontFeatureNamesPtr);
c._free(l._fontFeatureValuesPtr);c._free(l._fontVariationAxesPtr);c._free(l._fontVariationValuesPtr)}c.Paragraph.prototype.getRectsForRange=function(l,v,F,L){l=this._getRectsForRange(l,v,F,L);return e(l)};c.Paragraph.prototype.getRectsForPlaceholders=function(){var l=this._getRectsForPlaceholders();return e(l)};c.Paragraph.prototype.getGlyphInfoAt=function(l){return b(this._getGlyphInfoAt(l))};c.Paragraph.prototype.getClosestGlyphInfoAtCoordinate=function(l,v){return b(this._getClosestGlyphInfoAtCoordinate(l,
v))};c.TypefaceFontProvider.prototype.registerFont=function(l,v){l=c.Typeface.MakeTypefaceFromData(l);if(!l)return null;v=n(v);this._registerFont(l,v);l.delete()};c.ParagraphStyle=function(l){l.disableHinting=l.disableHinting||!1;if(l.ellipsis){var v=l.ellipsis;l._ellipsisPtr=n(v);l._ellipsisLen=ma(v)}else l._ellipsisPtr=G,l._ellipsisLen=0;null==l.heightMultiplier&&(l.heightMultiplier=-1);l.maxLines=l.maxLines||0;l.replaceTabCharacters=l.replaceTabCharacters||!1;v=(v=l.strutStyle)||{};v.strutEnabled=
v.strutEnabled||!1;v.strutEnabled&&Array.isArray(v.fontFamilies)&&v.fontFamilies.length?(v._fontFamiliesPtr=k(v.fontFamilies),v._fontFamiliesLen=v.fontFamilies.length):(v._fontFamiliesPtr=G,v._fontFamiliesLen=0);v.fontStyle=f(v.fontStyle);null==v.fontSize&&(v.fontSize=-1);null==v.heightMultiplier&&(v.heightMultiplier=-1);v.halfLeading=v.halfLeading||!1;v.leading=v.leading||0;v.forceStrutHeight=v.forceStrutHeight||!1;l.strutStyle=v;l.textAlign=l.textAlign||c.TextAlign.Start;l.textDirection=l.textDirection||
c.TextDirection.LTR;l.textHeightBehavior=l.textHeightBehavior||c.TextHeightBehavior.All;l.textStyle=c.TextStyle(l.textStyle);l.applyRoundingHack=!1!==l.applyRoundingHack;return l};c.TextStyle=function(l){l.color||(l.color=c.BLACK);l.decoration=l.decoration||0;l.decorationThickness=l.decorationThickness||0;l.decorationStyle=l.decorationStyle||c.DecorationStyle.Solid;l.textBaseline=l.textBaseline||c.TextBaseline.Alphabetic;null==l.fontSize&&(l.fontSize=-1);l.letterSpacing=l.letterSpacing||0;l.wordSpacing=
l.wordSpacing||0;null==l.heightMultiplier&&(l.heightMultiplier=-1);l.halfLeading=l.halfLeading||!1;l.fontStyle=f(l.fontStyle);return l};var C={},B=c._malloc(16),I=c._malloc(16),J=c._malloc(16);c.ParagraphBuilder.Make=function(l,v){u(l.textStyle);v=c.ParagraphBuilder._Make(l,v);x(l.textStyle);return v};c.ParagraphBuilder.MakeFromFontProvider=function(l,v){u(l.textStyle);v=c.ParagraphBuilder._MakeFromFontProvider(l,v);x(l.textStyle);return v};c.ParagraphBuilder.MakeFromFontCollection=function(l,v){u(l.textStyle);
v=c.ParagraphBuilder._MakeFromFontCollection(l,v);x(l.textStyle);return v};c.ParagraphBuilder.ShapeText=function(l,v,F){let L=0;for(const V of v)L+=V.length;if(L!==l.length)throw"Accumulated block lengths must equal text.length";return c.ParagraphBuilder._ShapeText(l,v,F)};c.ParagraphBuilder.prototype.pushStyle=function(l){u(l);this._pushStyle(l);x(l)};c.ParagraphBuilder.prototype.pushPaintStyle=function(l,v,F){u(l);this._pushPaintStyle(l,v,F);x(l)};c.ParagraphBuilder.prototype.addPlaceholder=function(l,
v,F,L,V){F=F||c.PlaceholderAlignment.Baseline;L=L||c.TextBaseline.Alphabetic;this._addPlaceholder(l||0,v||0,F,L,V||0)};c.ParagraphBuilder.prototype.setWordsUtf8=function(l){var v=q(l,"HEAPU32");this._setWordsUtf8(v,l&&l.length||0);p(v,l)};c.ParagraphBuilder.prototype.setWordsUtf16=function(l){var v=q(l,"HEAPU32");this._setWordsUtf16(v,l&&l.length||0);p(v,l)};c.ParagraphBuilder.prototype.setGraphemeBreaksUtf8=function(l){var v=q(l,"HEAPU32");this._setGraphemeBreaksUtf8(v,l&&l.length||0);p(v,l)};c.ParagraphBuilder.prototype.setGraphemeBreaksUtf16=
function(l){var v=q(l,"HEAPU32");this._setGraphemeBreaksUtf16(v,l&&l.length||0);p(v,l)};c.ParagraphBuilder.prototype.setLineBreaksUtf8=function(l){var v=q(l,"HEAPU32");this._setLineBreaksUtf8(v,l&&l.length||0);p(v,l)};c.ParagraphBuilder.prototype.setLineBreaksUtf16=function(l){var v=q(l,"HEAPU32");this._setLineBreaksUtf16(v,l&&l.length||0);p(v,l)}})})(E);a.Ka=a.Ka||[];a.Ka.push(function(){});a.Ka=a.Ka||[];a.Ka.push(function(){a.Canvas.prototype.drawText=function(c,b,e,f,k){var n=ma(c),u=a._malloc(n+
1);pa(c,u,n+1);this._drawSimpleText(u,n,b,e,k,f);a._free(u)};a.Canvas.prototype.drawGlyphs=function(c,b,e,f,k,n){if(!(2*c.length<=b.length))throw"Not enough positions for the array of gyphs";const u=q(c,"HEAPU16"),x=q(b,"HEAPF32");this._drawGlyphs(c.length,u,x,e,f,k,n);p(x,b);p(u,c)};a.Font.prototype.getGlyphBounds=function(c,b,e){var f=q(c,"HEAPU16"),k=a._malloc(16*c.length);this._getGlyphWidthBounds(f,c.length,G,k,b||null);b=new Float32Array(a.HEAPU8.buffer,k,4*c.length);p(f,c);if(e)return e.set(b),
a._free(k),e;c=Float32Array.from(b);a._free(k);return c};a.Font.prototype.getGlyphIDs=function(c,b,e){b||(b=c.length);var f=ma(c)+1,k=a._malloc(f);pa(c,k,f);c=a._malloc(2*b);b=this._getGlyphIDs(k,f-1,b,c);a._free(k);if(0>b)return a._free(c),null;k=new Uint16Array(a.HEAPU8.buffer,c,b);if(e)return e.set(k),a._free(c),e;e=Uint16Array.from(k);a._free(c);return e};a.Font.prototype.getGlyphIntercepts=function(c,b,e,f){var k=q(c,"HEAPU16"),n=q(b,"HEAPF32");return this._getGlyphIntercepts(k,c.length,!(c&&
c._ck),n,b.length,!(b&&b._ck),e,f)};a.Font.prototype.getGlyphWidths=function(c,b,e){var f=q(c,"HEAPU16"),k=a._malloc(4*c.length);this._getGlyphWidthBounds(f,c.length,k,G,b||null);b=new Float32Array(a.HEAPU8.buffer,k,c.length);p(f,c);if(e)return e.set(b),a._free(k),e;c=Float32Array.from(b);a._free(k);return c};a.FontMgr.FromData=function(){if(!arguments.length)return null;var c=arguments;1===c.length&&Array.isArray(c[0])&&(c=arguments[0]);if(!c.length)return null;for(var b=[],e=[],f=0;f<c.length;f++){var k=
new Uint8Array(c[f]),n=q(k,"HEAPU8");b.push(n);e.push(k.byteLength)}b=q(b,"HEAPU32");e=q(e,"HEAPU32");c=a.FontMgr._fromData(b,e,c.length);a._free(b);a._free(e);return c};a.Typeface.MakeTypefaceFromData=function(c){c=new Uint8Array(c);var b=q(c,"HEAPU8");return(c=a.Typeface._MakeTypefaceFromData(b,c.byteLength))?c:null};a.Typeface.MakeFreeTypeFaceFromData=a.Typeface.MakeTypefaceFromData;a.Typeface.prototype.getGlyphIDs=function(c,b,e){b||(b=c.length);var f=ma(c)+1,k=a._malloc(f);pa(c,k,f);c=a._malloc(2*
b);b=this._getGlyphIDs(k,f-1,b,c);a._free(k);if(0>b)return a._free(c),null;k=new Uint16Array(a.HEAPU8.buffer,c,b);if(e)return e.set(k),a._free(c),e;e=Uint16Array.from(k);a._free(c);return e};a.TextBlob.MakeOnPath=function(c,b,e,f){if(c&&c.length&&b&&b.countPoints()){if(1===b.countPoints())return this.MakeFromText(c,e);f||=0;var k=e.getGlyphIDs(c);k=e.getGlyphWidths(k);var n=[];b=new a.ContourMeasureIter(b,!1,1);for(var u=b.next(),x=new Float32Array(4),C=0;C<c.length&&u;C++){var B=k[C];f+=B/2;if(f>
u.length()){u.delete();u=b.next();if(!u){c=c.substring(0,C);break}f=B/2}u.getPosTan(f,x);var I=x[2],J=x[3];n.push(I,J,x[0]-B/2*I,x[1]-B/2*J);f+=B/2}c=this.MakeFromRSXform(c,n,e);u&&u.delete();b.delete();return c}};a.TextBlob.MakeFromRSXform=function(c,b,e){var f=ma(c)+1,k=a._malloc(f);pa(c,k,f);c=q(b,"HEAPF32");e=a.TextBlob._MakeFromRSXform(k,f-1,c,e);a._free(k);return e?e:null};a.TextBlob.MakeFromRSXformGlyphs=function(c,b,e){var f=q(c,"HEAPU16");b=q(b,"HEAPF32");e=a.TextBlob._MakeFromRSXformGlyphs(f,
2*c.length,b,e);p(f,c);return e?e:null};a.TextBlob.MakeFromGlyphs=function(c,b){var e=q(c,"HEAPU16");b=a.TextBlob._MakeFromGlyphs(e,2*c.length,b);p(e,c);return b?b:null};a.TextBlob.MakeFromText=function(c,b){var e=ma(c)+1,f=a._malloc(e);pa(c,f,e);c=a.TextBlob._MakeFromText(f,e-1,b);a._free(f);return c?c:null};a.MallocGlyphIDs=function(c){return a.Malloc(Uint16Array,c)}});a.Ka=a.Ka||[];a.Ka.push(function(){a.MakePicture=function(c){c=new Uint8Array(c);var b=a._malloc(c.byteLength);a.HEAPU8.set(c,b);
return(c=a._MakePicture(b,c.byteLength))?c:null}});a.Ka=a.Ka||[];a.Ka.push(function(){a.RuntimeEffect.Make=function(c,b){return a.RuntimeEffect._Make(c,{onError:b||function(e){console.log("RuntimeEffect error",e)}})};a.RuntimeEffect.MakeForBlender=function(c,b){return a.RuntimeEffect._MakeForBlender(c,{onError:b||function(e){console.log("RuntimeEffect error",e)}})};a.RuntimeEffect.prototype.makeShader=function(c,b){var e=!c._ck,f=q(c,"HEAPF32");b=w(b);return this._makeShader(f,4*c.length,e,b)};a.RuntimeEffect.prototype.makeShaderWithChildren=
function(c,b,e){var f=!c._ck,k=q(c,"HEAPF32");e=w(e);for(var n=[],u=0;u<b.length;u++)n.push(b[u].Ga.Ia);b=q(n,"HEAPU32");return this._makeShaderWithChildren(k,4*c.length,f,b,n.length,e)};a.RuntimeEffect.prototype.makeBlender=function(c){var b=!c._ck,e=q(c,"HEAPF32");return this._makeBlender(e,4*c.length,b)}})})(E);var qa="./this.program",ra=(a,d)=>{throw d;},va="",wa,xa;
if(la){var fs=require("fs"),Ha=require("path");import.meta.url.startsWith("data:")||(va=Ha.dirname(require("url").fileURLToPath(import.meta.url))+"/");xa=a=>{a=Ia(a)?new URL(a):a;return fs.readFileSync(a)};wa=async a=>{a=Ia(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(qa=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);ra=(a,d)=>{process.exitCode=a;throw d;}}else if(ja||ka)ka?va=self.location.href:"undefined"!=typeof document&&document.currentScript&&
(va=document.currentScript.src),_scriptName&&(va=_scriptName),va.startsWith("blob:")?va="":va=va.slice(0,va.replace(/[?#].*/,"").lastIndexOf("/")+1),ka&&(xa=a=>{var d=new XMLHttpRequest;d.open("GET",a,!1);d.responseType="arraybuffer";d.send(null);return new Uint8Array(d.response)}),wa=async a=>{if(Ia(a))return new Promise((g,h)=>{var m=new XMLHttpRequest;m.open("GET",a,!0);m.responseType="arraybuffer";m.onload=()=>{200==m.status||0==m.status&&m.response?g(m.response):h(m.status)};m.onerror=h;m.send(null)});
var d=await fetch(a,{credentials:"same-origin"});if(d.ok)return d.arrayBuffer();throw Error(d.status+" : "+d.url);};var Ka=console.log.bind(console),La=console.error.bind(console),Ma,Na=!1,Oa,Pa,Qa,Ta,H,N,Ua,Va,Wa,Xa,Ia=a=>a.startsWith("file://");
function Ya(){var a=Ma.buffer;Oa=new Int8Array(a);Qa=new Int16Array(a);E.HEAPU8=Pa=new Uint8Array(a);E.HEAPU16=Ta=new Uint16Array(a);E.HEAP32=H=new Int32Array(a);E.HEAPU32=N=new Uint32Array(a);E.HEAPF32=Ua=new Float32Array(a);Xa=new Float64Array(a);Va=new BigInt64Array(a);Wa=new BigUint64Array(a)}var Za=0,$a=null;function ab(a){a="Aborted("+a+")";La(a);Na=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ca(a);throw a;}var bb;
async function cb(a){try{var d=await wa(a);return new Uint8Array(d)}catch{}if(xa)a=xa(a);else throw"both async and sync fetching of the wasm failed";return a}async function db(a,d){try{var g=await cb(a);return await WebAssembly.instantiate(g,d)}catch(h){La(`failed to asynchronously prepare wasm: ${h}`),ab(h)}}
async function eb(a){var d=bb;if("function"==typeof WebAssembly.instantiateStreaming&&!Ia(d)&&!la)try{var g=fetch(d,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(g,a)}catch(h){La(`wasm streaming compile failed: ${h}`),La("falling back to ArrayBuffer instantiation")}return db(d,a)}class fb{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var gb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,hb=(a,d=0,g=NaN)=>{var h=d+g;for(g=d;a[g]&&!(g>=h);)++g;if(16<g-d&&a.buffer&&gb)return gb.decode(a.subarray(d,g));for(h="";d<g;){var m=a[d++];if(m&128){var r=a[d++]&63;if(192==(m&224))h+=String.fromCharCode((m&31)<<6|r);else{var t=a[d++]&63;m=224==(m&240)?(m&15)<<12|r<<6|t:(m&7)<<18|r<<12|t<<6|a[d++]&63;65536>m?h+=String.fromCharCode(m):(m-=65536,h+=String.fromCharCode(55296|m>>10,56320|m&1023))}}else h+=String.fromCharCode(m)}return h},
ib={},jb=a=>{for(;a.length;){var d=a.pop();a.pop()(d)}};function kb(a){return this.fromWireType(N[a>>2])}
var lb={},mb={},tb={},ub=E.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}},wb=(a,d,g)=>{function h(p){p=g(p);if(p.length!==a.length)throw new ub("Mismatched type converter count");for(var q=0;q<a.length;++q)vb(a[q],p[q])}a.forEach(p=>tb[p]=d);var m=Array(d.length),r=[],t=0;d.forEach((p,q)=>{mb.hasOwnProperty(p)?m[q]=mb[p]:(r.push(p),lb.hasOwnProperty(p)||(lb[p]=[]),lb[p].push(()=>{m[q]=mb[p];++t;t===r.length&&h(m)}))});0===r.length&&h(m)},xb=a=>{if(null===a)return"null";
var d=typeof a;return"object"===d||"array"===d||"function"===d?a.toString():""+a},yb,O=a=>{for(var d="";Pa[a];)d+=yb[Pa[a++]];return d},T=E.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
function zb(a,d,g={}){var h=d.name;if(!a)throw new T(`type "${h}" must have a positive integer typeid pointer`);if(mb.hasOwnProperty(a)){if(g.Ab)return;throw new T(`Cannot register type '${h}' twice`);}mb[a]=d;delete tb[a];lb.hasOwnProperty(a)&&(d=lb[a],delete lb[a],d.forEach(m=>m()))}function vb(a,d,g={}){return zb(a,d,g)}
var Ab=(a,d,g)=>{switch(d){case 1:return g?h=>Oa[h]:h=>Pa[h];case 2:return g?h=>Qa[h>>1]:h=>Ta[h>>1];case 4:return g?h=>H[h>>2]:h=>N[h>>2];case 8:return g?h=>Va[h>>3]:h=>Wa[h>>3];default:throw new TypeError(`invalid integer width (${d}): ${a}`);}},Bb=a=>{throw new T(a.Ga.Ja.Ha.name+" instance already deleted");},Cb=!1,Db=()=>{},Eb=a=>{if("undefined"===typeof FinalizationRegistry)return Eb=d=>d,a;Cb=new FinalizationRegistry(d=>{d=d.Ga;--d.count.value;0===d.count.value&&(d.Ma?d.Ra.Sa(d.Ma):d.Ja.Ha.Sa(d.Ia))});
Eb=d=>{var g=d.Ga;g.Ma&&Cb.register(d,{Ga:g},d);return d};Db=d=>{Cb.unregister(d)};return Eb(a)},Fb=[];function Gb(){}
var Ob=(a,d)=>Object.defineProperty(d,"name",{value:a}),Pb={},Qb=(a,d,g)=>{if(void 0===a[d].La){var h=a[d];a[d]=function(...m){if(!a[d].La.hasOwnProperty(m.length))throw new T(`Function '${g}' called with an invalid number of arguments (${m.length}) - expects one of (${a[d].La})!`);return a[d].La[m.length].apply(this,m)};a[d].La=[];a[d].La[h.Ua]=h}},Rb=(a,d,g)=>{if(E.hasOwnProperty(a)){if(void 0===g||void 0!==E[a].La&&void 0!==E[a].La[g])throw new T(`Cannot register public name '${a}' twice`);Qb(E,
a,a);if(E[a].La.hasOwnProperty(g))throw new T(`Cannot register multiple overloads of a function with the same number of arguments (${g})!`);E[a].La[g]=d}else E[a]=d,E[a].Ua=g},Sb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var d=a.charCodeAt(0);return 48<=d&&57>=d?`_${a}`:a};function Tb(a,d,g,h,m,r,t,p){this.name=a;this.constructor=d;this.Ta=g;this.Sa=h;this.Na=m;this.vb=r;this.ab=t;this.tb=p;this.Cb=[]}
var Ub=(a,d,g)=>{for(;d!==g;){if(!d.ab)throw new T(`Expected null or instance of ${g.name}, got an instance of ${d.name}`);a=d.ab(a);d=d.Na}return a};function Vb(a,d){if(null===d){if(this.ib)throw new T(`null is not a valid ${this.name}`);return 0}if(!d.Ga)throw new T(`Cannot pass "${xb(d)}" as a ${this.name}`);if(!d.Ga.Ia)throw new T(`Cannot pass deleted object as a pointer of type ${this.name}`);return Ub(d.Ga.Ia,d.Ga.Ja.Ha,this.Ha)}
function Wb(a,d){if(null===d){if(this.ib)throw new T(`null is not a valid ${this.name}`);if(this.fb){var g=this.jb();null!==a&&a.push(this.Sa,g);return g}return 0}if(!d||!d.Ga)throw new T(`Cannot pass "${xb(d)}" as a ${this.name}`);if(!d.Ga.Ia)throw new T(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.eb&&d.Ga.Ja.eb)throw new T(`Cannot convert argument of type ${d.Ga.Ra?d.Ga.Ra.name:d.Ga.Ja.name} to parameter type ${this.name}`);g=Ub(d.Ga.Ia,d.Ga.Ja.Ha,this.Ha);if(this.fb){if(void 0===
d.Ga.Ma)throw new T("Passing raw pointer to smart pointer is illegal");switch(this.Ib){case 0:if(d.Ga.Ra===this)g=d.Ga.Ma;else throw new T(`Cannot convert argument of type ${d.Ga.Ra?d.Ga.Ra.name:d.Ga.Ja.name} to parameter type ${this.name}`);break;case 1:g=d.Ga.Ma;break;case 2:if(d.Ga.Ra===this)g=d.Ga.Ma;else{var h=d.clone();g=this.Db(g,Xb(()=>h["delete"]()));null!==a&&a.push(this.Sa,g)}break;default:throw new T("Unsupporting sharing policy");}}return g}
function Yb(a,d){if(null===d){if(this.ib)throw new T(`null is not a valid ${this.name}`);return 0}if(!d.Ga)throw new T(`Cannot pass "${xb(d)}" as a ${this.name}`);if(!d.Ga.Ia)throw new T(`Cannot pass deleted object as a pointer of type ${this.name}`);if(d.Ga.Ja.eb)throw new T(`Cannot convert argument of type ${d.Ga.Ja.name} to parameter type ${this.name}`);return Ub(d.Ga.Ia,d.Ga.Ja.Ha,this.Ha)}
var Zb=(a,d,g)=>{if(d===g)return a;if(void 0===g.Na)return null;a=Zb(a,d,g.Na);return null===a?null:g.tb(a)},$b={},ac=(a,d)=>{if(void 0===d)throw new T("ptr should not be undefined");for(;a.Na;)d=a.ab(d),a=a.Na;return $b[d]},bc=(a,d)=>{if(!d.Ja||!d.Ia)throw new ub("makeClassHandle requires ptr and ptrType");if(!!d.Ra!==!!d.Ma)throw new ub("Both smartPtrType and smartPtr must be specified");d.count={value:1};return Eb(Object.create(a,{Ga:{value:d,writable:!0}}))};
function cc(a,d,g,h,m,r,t,p,q,y,w){this.name=a;this.Ha=d;this.ib=g;this.eb=h;this.fb=m;this.Bb=r;this.Ib=t;this.mb=p;this.jb=q;this.Db=y;this.Sa=w;m||void 0!==d.Na?this.toWireType=Wb:(this.toWireType=h?Vb:Yb,this.Qa=null)}
var dc=(a,d,g)=>{if(!E.hasOwnProperty(a))throw new ub("Replacing nonexistent public symbol");void 0!==E[a].La&&void 0!==g?E[a].La[g]=d:(E[a]=d,E[a].Ua=g)},U,W=(a,d)=>{a=O(a);var g=U.get(d);if("function"!=typeof g)throw new T(`unknown function pointer with signature ${a}: ${d}`);return g};class ec extends Error{}
var hc=a=>{a=fc(a);var d=O(a);gc(a);return d},ic=(a,d)=>{function g(r){m[r]||mb[r]||(tb[r]?tb[r].forEach(g):(h.push(r),m[r]=!0))}var h=[],m={};d.forEach(g);throw new ec(`${a}: `+h.map(hc).join([", "]));};function jc(a){for(var d=1;d<a.length;++d)if(null!==a[d]&&void 0===a[d].Qa)return!0;return!1}
function kc(a,d,g,h,m){var r=d.length;if(2>r)throw new T("argTypes array size mismatch! Must at least get return value and 'this' types!");var t=null!==d[1]&&null!==g,p=jc(d),q="void"!==d[0].name,y=r-2,w=Array(y),z=[],A=[];return Ob(a,function(...M){A.length=0;z.length=t?2:1;z[0]=m;if(t){var K=d[1].toWireType(A,this);z[1]=K}for(var D=0;D<y;++D)w[D]=d[D+2].toWireType(A,M[D]),z.push(w[D]);M=h(...z);if(p)jb(A);else for(D=t?1:2;D<d.length;D++){var Q=1===D?K:w[D-2];null!==d[D].Qa&&d[D].Qa(Q)}K=q?d[0].fromWireType(M):
void 0;return K})}
for(var lc=(a,d)=>{for(var g=[],h=0;h<a;h++)g.push(N[d+4*h>>2]);return g},mc=a=>{a=a.trim();const d=a.indexOf("(");return-1===d?a:a.slice(0,d)},nc=(a,d,g)=>{if(!(a instanceof Object))throw new T(`${g} with invalid "this": ${a}`);if(!(a instanceof d.Ha.constructor))throw new T(`${g} incompatible with "this" of type ${a.constructor.name}`);if(!a.Ga.Ia)throw new T(`cannot call emscripten binding method ${g} on deleted object`);return Ub(a.Ga.Ia,a.Ga.Ja.Ha,d.Ha)},qc=[],rc=[],sc=a=>{9<a&&0===--rc[a+1]&&
(rc[a]=void 0,qc.push(a))},tc=a=>{if(!a)throw new T(`Cannot use deleted val. handle = ${a}`);return rc[a]},Xb=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const d=qc.pop()||rc.length;rc[d]=a;rc[d+1]=1;return d}},uc={name:"emscripten::val",fromWireType:a=>{var d=tc(a);sc(a);return d},toWireType:(a,d)=>Xb(d),Oa:8,readValueFromPointer:kb,Qa:null},vc=(a,d,g)=>{switch(d){case 1:return g?function(h){return this.fromWireType(Oa[h])}:function(h){return this.fromWireType(Pa[h])};
case 2:return g?function(h){return this.fromWireType(Qa[h>>1])}:function(h){return this.fromWireType(Ta[h>>1])};case 4:return g?function(h){return this.fromWireType(H[h>>2])}:function(h){return this.fromWireType(N[h>>2])};default:throw new TypeError(`invalid integer width (${d}): ${a}`);}},wc=(a,d)=>{var g=mb[a];if(void 0===g)throw a=`${d} has unknown type ${hc(a)}`,new T(a);return g},xc=(a,d)=>{switch(d){case 4:return function(g){return this.fromWireType(Ua[g>>2])};case 8:return function(g){return this.fromWireType(Xa[g>>
3])};default:throw new TypeError(`invalid float width (${d}): ${a}`);}},pa=(a,d,g)=>{var h=Pa;if(!(0<g))return 0;var m=d;g=d+g-1;for(var r=0;r<a.length;++r){var t=a.charCodeAt(r);if(55296<=t&&57343>=t){var p=a.charCodeAt(++r);t=65536+((t&1023)<<10)|p&1023}if(127>=t){if(d>=g)break;h[d++]=t}else{if(2047>=t){if(d+1>=g)break;h[d++]=192|t>>6}else{if(65535>=t){if(d+2>=g)break;h[d++]=224|t>>12}else{if(d+3>=g)break;h[d++]=240|t>>18;h[d++]=128|t>>12&63}h[d++]=128|t>>6&63}h[d++]=128|t&63}}h[d]=0;return d-m},
ma=a=>{for(var d=0,g=0;g<a.length;++g){var h=a.charCodeAt(g);127>=h?d++:2047>=h?d+=2:55296<=h&&57343>=h?(d+=4,++g):d+=3}return d},yc="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,zc=(a,d)=>{var g=a>>1;for(var h=g+d/2;!(g>=h)&&Ta[g];)++g;g<<=1;if(32<g-a&&yc)return yc.decode(Pa.subarray(a,g));g="";for(h=0;!(h>=d/2);++h){var m=Qa[a+2*h>>1];if(0==m)break;g+=String.fromCharCode(m)}return g},Ac=(a,d,g)=>{g??=2147483647;if(2>g)return 0;g-=2;var h=d;g=g<2*a.length?g/2:a.length;for(var m=
0;m<g;++m)Qa[d>>1]=a.charCodeAt(m),d+=2;Qa[d>>1]=0;return d-h},Bc=a=>2*a.length,Cc=(a,d)=>{for(var g=0,h="";!(g>=d/4);){var m=H[a+4*g>>2];if(0==m)break;++g;65536<=m?(m-=65536,h+=String.fromCharCode(55296|m>>10,56320|m&1023)):h+=String.fromCharCode(m)}return h},Dc=(a,d,g)=>{g??=2147483647;if(4>g)return 0;var h=d;g=h+g-4;for(var m=0;m<a.length;++m){var r=a.charCodeAt(m);if(55296<=r&&57343>=r){var t=a.charCodeAt(++m);r=65536+((r&1023)<<10)|t&1023}H[d>>2]=r;d+=4;if(d+4>g)break}H[d>>2]=0;return d-h},Ec=
a=>{for(var d=0,g=0;g<a.length;++g){var h=a.charCodeAt(g);55296<=h&&57343>=h&&++g;d+=4}return d},Fc=(a,d,g)=>{var h=[];a=a.toWireType(h,g);h.length&&(N[d>>2]=Xb(h));return a},Gc=[],Hc={},Ic=a=>{var d=Hc[a];return void 0===d?O(a):d},Jc=()=>{function a(d){d.$$$embind_global$$$=d;var g="object"==typeof $$$embind_global$$$&&d.$$$embind_global$$$==d;g||delete d.$$$embind_global$$$;return g}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;
"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");},Kc=a=>{var d=Gc.length;Gc.push(a);return d},Lc=(a,d)=>{for(var g=Array(a),h=0;h<a;++h)g[h]=wc(N[d+4*h>>2],`parameter ${h}`);return g},Mc=Reflect.construct,Nc={},Pc=()=>{if(!Oc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==
typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:qa||"./this.program"},d;for(d in Nc)void 0===Nc[d]?delete a[d]:a[d]=Nc[d];var g=[];for(d in a)g.push(`${d}=${a[d]}`);Oc=g}return Oc},Oc,Qc=[null,[],[]],Rc=Array(256),Sc=0;256>Sc;++Sc)Rc[Sc]=String.fromCharCode(Sc);yb=Rc;
(()=>{let a=Gb.prototype;Object.assign(a,{isAliasOf:function(g){if(!(this instanceof Gb&&g instanceof Gb))return!1;var h=this.Ga.Ja.Ha,m=this.Ga.Ia;g.Ga=g.Ga;var r=g.Ga.Ja.Ha;for(g=g.Ga.Ia;h.Na;)m=h.ab(m),h=h.Na;for(;r.Na;)g=r.ab(g),r=r.Na;return h===r&&m===g},clone:function(){this.Ga.Ia||Bb(this);if(this.Ga.$a)return this.Ga.count.value+=1,this;var g=Eb,h=Object,m=h.create,r=Object.getPrototypeOf(this),t=this.Ga;g=g(m.call(h,r,{Ga:{value:{count:t.count,Za:t.Za,$a:t.$a,Ia:t.Ia,Ja:t.Ja,Ma:t.Ma,Ra:t.Ra}}}));
g.Ga.count.value+=1;g.Ga.Za=!1;return g},["delete"](){this.Ga.Ia||Bb(this);if(this.Ga.Za&&!this.Ga.$a)throw new T("Object already scheduled for deletion");Db(this);var g=this.Ga;--g.count.value;0===g.count.value&&(g.Ma?g.Ra.Sa(g.Ma):g.Ja.Ha.Sa(g.Ia));this.Ga.$a||(this.Ga.Ma=void 0,this.Ga.Ia=void 0)},isDeleted:function(){return!this.Ga.Ia},deleteLater:function(){this.Ga.Ia||Bb(this);if(this.Ga.Za&&!this.Ga.$a)throw new T("Object already scheduled for deletion");Fb.push(this);this.Ga.Za=!0;return this}});
const d=Symbol.dispose;d&&(a[d]=a["delete"])})();
Object.assign(cc.prototype,{wb(a){this.mb&&(a=this.mb(a));return a},kb(a){this.Sa?.(a)},Oa:8,readValueFromPointer:kb,fromWireType:function(a){function d(){return this.fb?bc(this.Ha.Ta,{Ja:this.Bb,Ia:g,Ra:this,Ma:a}):bc(this.Ha.Ta,{Ja:this,Ia:a})}var g=this.wb(a);if(!g)return this.kb(a),null;var h=ac(this.Ha,g);if(void 0!==h){if(0===h.Ga.count.value)return h.Ga.Ia=g,h.Ga.Ma=a,h.clone();h=h.clone();this.kb(a);return h}h=this.Ha.vb(g);h=Pb[h];if(!h)return d.call(this);h=this.eb?h.sb:h.pointerType;var m=
Zb(g,this.Ha,h.Ha);return null===m?d.call(this):this.fb?bc(h.Ha.Ta,{Ja:h,Ia:m,Ra:this,Ma:a}):bc(h.Ha.Ta,{Ja:h,Ia:m})}});rc.push(0,1,void 0,1,null,1,!0,1,!1,1);E.count_emval_handles=()=>rc.length/2-5-qc.length;
var kd={O:function(){return 0},ha:()=>{},ja:function(){return 0},ea:()=>{},fa:()=>{},P:function(){},ga:()=>{},la:()=>ab(""),A:a=>{var d=ib[a];delete ib[a];var g=d.jb,h=d.Sa,m=d.lb,r=m.map(t=>t.zb).concat(m.map(t=>t.Gb));wb([a],r,t=>{var p={};m.forEach((q,y)=>{var w=t[y],z=q.xb,A=q.yb,M=t[y+m.length],K=q.Fb,D=q.Hb;p[q.ub]={read:Q=>w.fromWireType(z(A,Q)),write:(Q,ea)=>{var R=[];K(D,Q,M.toWireType(R,ea));jb(R)},optional:t[y].optional}});return[{name:d.name,fromWireType:q=>{var y={},w;for(w in p)y[w]=
p[w].read(q);h(q);return y},toWireType:(q,y)=>{for(var w in p)if(!(w in y||p[w].optional))throw new TypeError(`Missing field: "${w}"`);var z=g();for(w in p)p[w].write(z,y[w]);null!==q&&q.push(h,z);return z},Oa:8,readValueFromPointer:kb,Qa:h}]})},V:(a,d,g)=>{d=O(d);vb(a,{name:d,fromWireType:h=>h,toWireType:function(h,m){if("bigint"!=typeof m&&"number"!=typeof m)throw new TypeError(`Cannot convert "${xb(m)}" to ${this.name}`);"number"==typeof m&&(m=BigInt(m));return m},Oa:8,readValueFromPointer:Ab(d,
g,-1==d.indexOf("u")),Qa:null})},va:(a,d,g,h)=>{d=O(d);vb(a,{name:d,fromWireType:function(m){return!!m},toWireType:function(m,r){return r?g:h},Oa:8,readValueFromPointer:function(m){return this.fromWireType(Pa[m])},Qa:null})},k:(a,d,g,h,m,r,t,p,q,y,w,z,A)=>{w=O(w);r=W(m,r);p&&=W(t,p);y&&=W(q,y);A=W(z,A);var M=Sb(w);Rb(M,function(){ic(`Cannot construct ${w} due to unbound types`,[h])});wb([a,d,g],h?[h]:[],K=>{K=K[0];if(h){var D=K.Ha;var Q=D.Ta}else Q=Gb.prototype;K=Ob(w,function(...da){if(Object.getPrototypeOf(this)!==
ea)throw new T(`Use 'new' to construct ${w}`);if(void 0===R.Va)throw new T(`${w} has no accessible constructor`);var ya=R.Va[da.length];if(void 0===ya)throw new T(`Tried to invoke ctor of ${w} with invalid number of parameters (${da.length}) - expected (${Object.keys(R.Va).toString()}) parameters instead!`);return ya.apply(this,da)});var ea=Object.create(Q,{constructor:{value:K}});K.prototype=ea;var R=new Tb(w,K,ea,A,D,r,p,y);if(R.Na){var ia;(ia=R.Na).bb??(ia.bb=[]);R.Na.bb.push(R)}D=new cc(w,R,!0,
!1,!1);ia=new cc(w+"*",R,!1,!1,!1);Q=new cc(w+" const*",R,!1,!0,!1);Pb[a]={pointerType:ia,sb:Q};dc(M,K);return[D,ia,Q]})},e:(a,d,g,h,m,r,t)=>{var p=lc(g,h);d=O(d);d=mc(d);r=W(m,r);wb([],[a],q=>{function y(){ic(`Cannot call ${w} due to unbound types`,p)}q=q[0];var w=`${q.name}.${d}`;d.startsWith("@@")&&(d=Symbol[d.substring(2)]);var z=q.Ha.constructor;void 0===z[d]?(y.Ua=g-1,z[d]=y):(Qb(z,d,w),z[d].La[g-1]=y);wb([],p,A=>{A=[A[0],null].concat(A.slice(1));A=kc(w,A,null,r,t);void 0===z[d].La?(A.Ua=g-
1,z[d]=A):z[d].La[g-1]=A;if(q.Ha.bb)for(const M of q.Ha.bb)M.constructor.hasOwnProperty(d)||(M.constructor[d]=A);return[]});return[]})},w:(a,d,g,h,m,r)=>{var t=lc(d,g);m=W(h,m);wb([],[a],p=>{p=p[0];var q=`constructor ${p.name}`;void 0===p.Ha.Va&&(p.Ha.Va=[]);if(void 0!==p.Ha.Va[d-1])throw new T(`Cannot register multiple constructors with identical number of parameters (${d-1}) for class '${p.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
p.Ha.Va[d-1]=()=>{ic(`Cannot construct ${p.name} due to unbound types`,t)};wb([],t,y=>{y.splice(1,0,null);p.Ha.Va[d-1]=kc(q,y,null,m,r);return[]});return[]})},a:(a,d,g,h,m,r,t,p)=>{var q=lc(g,h);d=O(d);d=mc(d);r=W(m,r);wb([],[a],y=>{function w(){ic(`Cannot call ${z} due to unbound types`,q)}y=y[0];var z=`${y.name}.${d}`;d.startsWith("@@")&&(d=Symbol[d.substring(2)]);p&&y.Ha.Cb.push(d);var A=y.Ha.Ta,M=A[d];void 0===M||void 0===M.La&&M.className!==y.name&&M.Ua===g-2?(w.Ua=g-2,w.className=y.name,A[d]=
w):(Qb(A,d,z),A[d].La[g-2]=w);wb([],q,K=>{K=kc(z,K,y,r,t);void 0===A[d].La?(K.Ua=g-2,A[d]=K):A[d].La[g-2]=K;return[]});return[]})},C:(a,d,g,h,m,r,t,p,q,y)=>{d=O(d);m=W(h,m);wb([],[a],w=>{w=w[0];var z=`${w.name}.${d}`,A={get(){ic(`Cannot access ${z} due to unbound types`,[g,t])},enumerable:!0,configurable:!0};A.set=q?()=>ic(`Cannot access ${z} due to unbound types`,[g,t]):()=>{throw new T(z+" is a read-only property");};Object.defineProperty(w.Ha.Ta,d,A);wb([],q?[g,t]:[g],M=>{var K=M[0],D={get(){var ea=
nc(this,w,z+" getter");return K.fromWireType(m(r,ea))},enumerable:!0};if(q){q=W(p,q);var Q=M[1];D.set=function(ea){var R=nc(this,w,z+" setter"),ia=[];q(y,R,Q.toWireType(ia,ea));jb(ia)}}Object.defineProperty(w.Ha.Ta,d,D);return[]});return[]})},v:(a,d,g)=>{a=O(a);wb([],[d],h=>{h=h[0];E[a]=h.fromWireType(g);return[]})},ta:a=>vb(a,uc),l:(a,d,g,h)=>{function m(){}d=O(d);m.values={};vb(a,{name:d,constructor:m,fromWireType:function(r){return this.constructor.values[r]},toWireType:(r,t)=>t.value,Oa:8,readValueFromPointer:vc(d,
g,h),Qa:null});Rb(d,m)},b:(a,d,g)=>{var h=wc(a,"enum");d=O(d);a=h.constructor;h=Object.create(h.constructor.prototype,{value:{value:g},constructor:{value:Ob(`${h.name}_${d}`,function(){})}});a.values[g]=h;a[d]=h},U:(a,d,g)=>{d=O(d);vb(a,{name:d,fromWireType:h=>h,toWireType:(h,m)=>m,Oa:8,readValueFromPointer:xc(d,g),Qa:null})},D:(a,d,g,h,m,r)=>{var t=lc(d,g);a=O(a);a=mc(a);m=W(h,m);Rb(a,function(){ic(`Cannot call ${a} due to unbound types`,t)},d-1);wb([],t,p=>{p=[p[0],null].concat(p.slice(1));dc(a,
kc(a,p,null,m,r),d-1);return[]})},E:(a,d,g,h,m)=>{d=O(d);-1===m&&(m=4294967295);m=p=>p;if(0===h){var r=32-8*g;m=p=>p<<r>>>r}var t=d.includes("unsigned")?function(p,q){return q>>>0}:function(p,q){return q};vb(a,{name:d,fromWireType:m,toWireType:t,Oa:8,readValueFromPointer:Ab(d,g,0!==h),Qa:null})},t:(a,d,g)=>{function h(r){return new m(Oa.buffer,N[r+4>>2],N[r>>2])}var m=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][d];g=O(g);
vb(a,{name:g,fromWireType:h,Oa:8,readValueFromPointer:h},{Ab:!0})},r:(a,d,g,h,m,r,t,p,q,y,w,z)=>{g=O(g);r=W(m,r);p=W(t,p);y=W(q,y);z=W(w,z);wb([a],[d],A=>{A=A[0];return[new cc(g,A.Ha,!1,!1,!0,A,h,r,p,y,z)]})},ua:(a,d)=>{d=O(d);vb(a,{name:d,fromWireType:function(g){for(var h=N[g>>2],m=g+4,r,t=m,p=0;p<=h;++p){var q=m+p;if(p==h||0==Pa[q])t=t?hb(Pa,t,q-t):"",void 0===r?r=t:(r+=String.fromCharCode(0),r+=t),t=q+1}gc(g);return r},toWireType:function(g,h){h instanceof ArrayBuffer&&(h=new Uint8Array(h));var m=
"string"==typeof h;if(!(m||ArrayBuffer.isView(h)&&1==h.BYTES_PER_ELEMENT))throw new T("Cannot pass non-string to std::string");var r=m?ma(h):h.length;var t=Tc(4+r+1),p=t+4;N[t>>2]=r;m?pa(h,p,r+1):Pa.set(h,p);null!==g&&g.push(gc,t);return t},Oa:8,readValueFromPointer:kb,Qa(g){gc(g)}})},L:(a,d,g)=>{g=O(g);if(2===d){var h=zc;var m=Ac;var r=Bc;var t=p=>Ta[p>>1]}else 4===d&&(h=Cc,m=Dc,r=Ec,t=p=>N[p>>2]);vb(a,{name:g,fromWireType:p=>{for(var q=N[p>>2],y,w=p+4,z=0;z<=q;++z){var A=p+4+z*d;if(z==q||0==t(A))w=
h(w,A-w),void 0===y?y=w:(y+=String.fromCharCode(0),y+=w),w=A+d}gc(p);return y},toWireType:(p,q)=>{if("string"!=typeof q)throw new T(`Cannot pass non-string to C++ string type ${g}`);var y=r(q),w=Tc(4+y+d);N[w>>2]=y/d;m(q,w+4,y+d);null!==p&&p.push(gc,w);return w},Oa:8,readValueFromPointer:kb,Qa(p){gc(p)}})},B:(a,d,g,h,m,r)=>{ib[a]={name:O(d),jb:W(g,h),Sa:W(m,r),lb:[]}},d:(a,d,g,h,m,r,t,p,q,y)=>{ib[a].lb.push({ub:O(d),zb:g,xb:W(h,m),yb:r,Gb:t,Fb:W(p,q),Hb:y})},wa:(a,d)=>{d=O(d);vb(a,{Jb:!0,name:d,Oa:0,
fromWireType:()=>{},toWireType:()=>{}})},X:()=>{throw Infinity;},F:(a,d,g)=>{a=tc(a);d=wc(d,"emval::as");return Fc(d,g,a)},K:(a,d,g,h)=>{a=Gc[a];d=tc(d);return a(null,d,g,h)},x:(a,d,g,h,m)=>{a=Gc[a];d=tc(d);g=Ic(g);return a(d,d[g],h,m)},c:sc,M:a=>{if(0===a)return Xb(Jc());a=Ic(a);return Xb(Jc()[a])},u:(a,d,g)=>{var h=Lc(a,d),m=h.shift();a--;var r=Array(a);d=`methodCaller<(${h.map(t=>t.name).join(", ")}) => ${m.name}>`;return Kc(Ob(d,(t,p,q,y)=>{for(var w=0,z=0;z<a;++z)r[z]=h[z].readValueFromPointer(y+
w),w+=h[z].Oa;t=1===g?Mc(p,r):p.apply(t,r);return Fc(m,q,t)}))},z:(a,d)=>{a=tc(a);d=tc(d);return Xb(a[d])},T:a=>{9<a&&(rc[a+1]+=1)},I:()=>Xb([]),f:a=>Xb(Ic(a)),G:()=>Xb({}),sa:a=>{a=tc(a);return!a},n:a=>{var d=tc(a);jb(d);sc(a)},i:(a,d,g)=>{a=tc(a);d=tc(d);g=tc(g);a[d]=g},g:(a,d)=>{a=wc(a,"_emval_take_value");a=a.readValueFromPointer(d);return Xb(a)},aa:function(a,d){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);H[d>>2]=a.getUTCSeconds();H[d+4>>2]=a.getUTCMinutes();H[d+
8>>2]=a.getUTCHours();H[d+12>>2]=a.getUTCDate();H[d+16>>2]=a.getUTCMonth();H[d+20>>2]=a.getUTCFullYear()-1900;H[d+24>>2]=a.getUTCDay();H[d+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},_:function(){return-52},$:function(){},ma:(a,d,g,h)=>{var m=(new Date).getFullYear(),r=(new Date(m,0,1)).getTimezoneOffset();m=(new Date(m,6,1)).getTimezoneOffset();N[a>>2]=60*Math.max(r,m);H[d>>2]=Number(r!=m);d=t=>{var p=Math.abs(t);return`UTC${0<=t?"-":"+"}${String(Math.floor(p/60)).padStart(2,
"0")}${String(p%60).padStart(2,"0")}`};a=d(r);d=d(m);m<r?(pa(a,g,17),pa(d,h,17)):(pa(a,h,17),pa(d,g,17))},W:function(a,d,g){if(!(0<=a&&3>=a))return 28;Va[g>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},ka:()=>Date.now(),Y:a=>{var d=Pa.length;a>>>=0;if(2147483648<a)return!1;for(var g=1;4>=g;g*=2){var h=d*(1+.2/g);h=Math.min(h,a+100663296);a:{h=(Math.min(2147483648,65536*Math.ceil(Math.max(a,h)/65536))-Ma.buffer.byteLength+65535)/65536|0;try{Ma.grow(h);Ya();var m=1;break a}catch(r){}m=
void 0}if(m)return!0}return!1},ca:(a,d)=>{var g=0,h=0,m;for(m of Pc()){var r=d+g;N[a+h>>2]=r;g+=pa(m,r,Infinity)+1;h+=4}return 0},da:(a,d)=>{var g=Pc();N[a>>2]=g.length;a=0;for(var h of g)a+=ma(h)+1;N[d>>2]=a;return 0},na:a=>{ra(a,new fb(a))},J:()=>52,Z:function(){return 52},ia:()=>52,ba:function(){return 70},N:(a,d,g,h)=>{for(var m=0,r=0;r<g;r++){var t=N[d>>2],p=N[d+4>>2];d+=8;for(var q=0;q<p;q++){var y=a,w=Pa[t+q],z=Qc[y];0===w||10===w?((1===y?Ka:La)(hb(z)),z.length=0):z.push(w)}m+=p}N[h>>2]=m;
return 0},oa:Uc,h:Vc,q:Wc,j:Xc,y:Yc,S:Zc,R:$c,Q:ad,H:bd,m:cd,o:dd,s:ed,p:fd,ra:gd,pa:hd,qa:jd},ld=await (async function(){Za++;var a={a:kd};bb??=E.locateFile?E.locateFile?E.locateFile("canvaskit.wasm",va):va+"canvaskit.wasm":(new URL("canvaskit.wasm",import.meta.url)).href;try{return ld=(await eb(a)).instance.exports,Ma=ld.xa,Ya(),U=ld.Aa,Za--,0==Za&&$a&&(a=$a,$a=null,a()),ld}catch(d){return ca(d),Promise.reject(d)}}()),fc=ld.za,Tc=E._malloc=ld.Ba,gc=E._free=ld.Ca,X=ld.Da,Y=ld.Ea,
Z=ld.Fa;function Xc(a,d,g,h){var m=Z();try{return U.get(a)(d,g,h)}catch(r){Y(m);if(r!==r+0)throw r;X(1,0)}}function gd(a,d,g,h,m,r){var t=Z();try{U.get(a)(d,g,h,m,r)}catch(p){Y(t);if(p!==p+0)throw p;X(1,0)}}function fd(a,d,g,h,m){var r=Z();try{U.get(a)(d,g,h,m)}catch(t){Y(r);if(t!==t+0)throw t;X(1,0)}}function dd(a,d,g){var h=Z();try{U.get(a)(d,g)}catch(m){Y(h);if(m!==m+0)throw m;X(1,0)}}function Yc(a,d,g,h,m){var r=Z();try{return U.get(a)(d,g,h,m)}catch(t){Y(r);if(t!==t+0)throw t;X(1,0)}}
function Vc(a,d){var g=Z();try{return U.get(a)(d)}catch(h){Y(g);if(h!==h+0)throw h;X(1,0)}}function ed(a,d,g,h){var m=Z();try{U.get(a)(d,g,h)}catch(r){Y(m);if(r!==r+0)throw r;X(1,0)}}function cd(a,d){var g=Z();try{U.get(a)(d)}catch(h){Y(g);if(h!==h+0)throw h;X(1,0)}}function jd(a,d,g,h,m,r,t,p,q,y){var w=Z();try{U.get(a)(d,g,h,m,r,t,p,q,y)}catch(z){Y(w);if(z!==z+0)throw z;X(1,0)}}function bd(a){var d=Z();try{U.get(a)()}catch(g){Y(d);if(g!==g+0)throw g;X(1,0)}}
function Wc(a,d,g){var h=Z();try{return U.get(a)(d,g)}catch(m){Y(h);if(m!==m+0)throw m;X(1,0)}}function hd(a,d,g,h,m,r,t){var p=Z();try{U.get(a)(d,g,h,m,r,t)}catch(q){Y(p);if(q!==q+0)throw q;X(1,0)}}function Uc(a){var d=Z();try{return U.get(a)()}catch(g){Y(d);if(g!==g+0)throw g;X(1,0)}}function Zc(a,d,g,h,m,r,t){var p=Z();try{return U.get(a)(d,g,h,m,r,t)}catch(q){Y(p);if(q!==q+0)throw q;X(1,0)}}
function $c(a,d,g,h,m,r,t,p){var q=Z();try{return U.get(a)(d,g,h,m,r,t,p)}catch(y){Y(q);if(y!==y+0)throw y;X(1,0)}}function ad(a,d,g,h,m,r,t,p,q,y){var w=Z();try{return U.get(a)(d,g,h,m,r,t,p,q,y)}catch(z){Y(w);if(z!==z+0)throw z;X(1,0)}}function md(){0<Za?$a=md:0<Za?$a=md:(E.calledRun=!0,Na||(ld.ya(),ba(E),E.onRuntimeInitialized?.()))}md();moduleRtn=ha;


  return moduleRtn;
}
);
})();
export default CanvasKitInit;
